spring.application.name=LinkLyticsApp
spring.datasource.url=jdbc:mysql://localhost:3306/linklytics
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

## JWT configuration
# Use a base64-encoded secret (recommended length: at least 256 bits). You can generate one with
# `openssl rand -base64 32` and paste here.
jwt.secret=Z3VucmVsbF9zZWN1cmVfc2VjcmV0X2Zvcl9kZW1vX3B1cnBvc2VzMTIzNDU2
# Expiration in milliseconds (default: 86400000 = 1 day)
jwt.expiration=86400000
